name: init

on:
  workflow_dispatch:
  schedule:
    # Horários no formato cron (UTC)
    - cron: '0 9 * * *'   # Executa às 6:00   Brasilia
    - cron: '0 15 * * *'  # Executa às 12:00  Brasilia
    - cron: '0 00 * * *'  # Executa às 21:00  Brasilia
    
permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-22.04

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}

    steps:
      - name: Cache pip and other dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.13/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: Install ImageMagick
        run: |
          sudo apt-get install -y imagemagick || { echo 'ImageMagick installation failed'; exit 1; }

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
          architecture: x64

      - name: Upgrade pip to latest stable
        run: |
          python -m pip install --upgrade pip || { echo 'Pip upgrade failed'; exit 1; }

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt || { echo 'Dependency installation failed'; exit 1; }

      - name: Run Python script
        run: python -m src.main || { echo 'Script execution failed'; exit 1; }

      - name: Update replyed_ids.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "updated"
          file_pattern: history/*.txt history/app.log
          push_options: '--force'
