name: init

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

permissions:
  contents: write
  actions: write

jobs:
  init:
    runs-on: ubuntu-latest

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}

    steps:
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: install imagemagick
        run: |
          sudo apt-get install -y imagemagick

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
          architecture: x64

      - name: Upgrade pip to latest stable
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Update replyed_ids.txt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          file_pattern: history/*.txt
          push_options: '--force'
